"""Sourced object dossier (Layer 3): ``ai_query`` over governed tables, with checked citations."""

from __future__ import annotations

import datetime as dt
import re
from typing import TYPE_CHECKING

from .heroes import load_heroes

if TYPE_CHECKING:
    from pyspark.sql import Row, SparkSession

    from .config import Config


def retrieve(
    spark: SparkSession, cfg: Config, object_id: str, limit: int = 10
) -> list[Row]:
    """Reports linked to an object by candidate-pair probability (>= 0.3), strongest first."""
    return spark.sql(f"""
      SELECT r.report_id, p.obs_id, round(p.match_prob, 3) AS match_prob, b.producer, r.report_text
      FROM {cfg.s}.silver_scored_pairs p
      JOIN {cfg.s}.bronze_reports r ON r.obs_id = p.obs_id
      JOIN {cfg.s}.bronze_observations b ON b.obs_id = p.obs_id
      WHERE p.object_id = '{object_id}' AND p.match_prob >= 0.3
      ORDER BY p.match_prob DESC LIMIT {limit}""").collect()


def template_dossier(obj: Row, rows: list[Row]) -> str:
    """No-LLM fallback dossier: the object, its strongest linked report and the next action."""
    top = rows[0]
    return (
        f"{obj.object_type} {obj.designator} (system ID {obj.object_id}) is in the object system with "
        f"{len(rows)} linked reports. "
        f"Strongest link: [{top.report_id}] at match probability {top.match_prob}. "
        f"Recommended action: analyst review of the linked reports."
    )


def build_dossier(
    spark: SparkSession, cfg: Config, object_id: str
) -> tuple[str, list[str], str]:
    """Generate one object's dossier and check that it cites only retrieved reports.

    An ``ai_query`` error or a citation outside the retrieved set falls back to the template
    dossier, labelled as such, so a live demo never shows an unsupported claim.

    :return: (dossier text, cited report IDs, what generated it).
    """
    obj = spark.sql(
        f"SELECT * FROM {cfg.s}.oms_objects WHERE object_id = '{object_id}'"
    ).first()
    rows = retrieve(spark, cfg, object_id)
    assert rows, f"no linked reports for {object_id}"
    allowed = {r.report_id for r in rows}
    context = "\n".join(
        f"[{r.report_id}] ({r.producer}, match probability {r.match_prob}) {r.report_text}"
        for r in rows
    )
    prompt = (
        f"You are assisting an analyst. Object {obj.object_type} {obj.designator} (system ID {obj.object_id}) "
        f"is in the object management system. Refer to it as {obj.object_type} {obj.designator}. "
        f"Using ONLY the reports below, write a 4-sentence dossier: what the "
        f"object is, how consistently it has been observed, any uncertainty, and a recommended analyst action. "
        f"Cite report IDs in square brackets, one ID per bracket. Synthetic data.\n\nReports:\n{context}"
    )
    assert "true_object_id" not in prompt, "ground truth must not reach the prompt"
    try:
        text = (
            spark.sql(
                f"SELECT ai_query('{cfg.ai_endpoint}', :prompt) AS d",
                args={"prompt": prompt},
            )
            .first()
            .d
        )
    except Exception as e:  # live-demo safety: say so, then fall back
        print(
            f"ai_query failed for {object_id} ({type(e).__name__}); using template dossier"
        )
        return (
            template_dossier(obj, rows),
            [rows[0].report_id],
            "template (ai_query error)",
        )
    cited = {
        c.strip() for grp in re.findall(r"\[([^\]]+)\]", text) for c in grp.split(",")
    }
    if not cited or not cited <= allowed:
        print(
            f"citation check FAILED for {object_id}: unknown or missing IDs {sorted(cited - allowed)}"
        )
        return (
            template_dossier(obj, rows),
            [rows[0].report_id],
            "template (citation check failed)",
        )
    return text, sorted(cited), cfg.ai_endpoint


def build_hero_dossiers(spark: SparkSession, cfg: Config) -> dict:
    """Write ``object_dossiers`` for heroes A and B (C is a nomination: it has no scored pairs to cite).

    :return: no facts (empty dict).
    """
    heroes = load_heroes(spark, cfg)
    dossiers = []
    for hero in ["A", "B"]:
        oid = heroes[hero].object_id
        text, cited, by = build_dossier(spark, cfg, oid)
        now = dt.datetime.now(dt.UTC).replace(tzinfo=None)
        dossiers.append((oid, hero, text, cited, True, by, now))
        print(f"\n=== Hero {hero}: {oid} (generated by {by}) ===\n{text}")
    # citations_valid is always true: a dossier that fails the check is replaced by the template.
    spark.createDataFrame(
        dossiers,
        "object_id STRING, hero STRING, dossier_text STRING, cited_ids ARRAY<STRING>, "
        "citations_valid BOOLEAN, generated_by STRING, generated_at TIMESTAMP",
    ).write.mode("overwrite").saveAsTable(f"{cfg.s}.object_dossiers")
    return {}
